import type { EOBExtractionRecord, EOBLineItem } from "@/lib/extraction/types";

export type ReviewStatus = "pending" | "approved" | "flagged" | "rejected";

export interface DemoClaim {
  id: string;
  patient_name: string;
  payer_name: string;
  claim_number: string;
  date_of_service: string;
  created_at: string;
  check_amount: number;
  review_status: ReviewStatus;
  confidence_score: number;
  provider_name: string;
  provider_npi: string;
  payer_id: string;
  patient_id: string;
  subscriber_id: string;
  check_number: string;
  check_date: string;
  total_billed: number;
  total_allowed: number;
  total_insurance_paid: number;
  total_patient_responsibility: number;
  total_adjustments: number;
  line_items: EOBLineItem[];
  note: string;
}

const practice = "Northwind Dental (fictional)";

export const DEMO_BATCH_NAME = "Sample batch · Northwind Dental";

export const initialDemoClaims: DemoClaim[] = [
  {
    id: "maple",
    patient_name: "Maple Quill",
    payer_name: "Lumen Dental Plan",
    claim_number: "LMN-1044",
    date_of_service: "2025-10-14",
    created_at: "2025-11-02T15:00:00.000Z",
    check_amount: 210,
    review_status: "approved",
    confidence_score: 0.96,
    provider_name: practice,
    provider_npi: "1999999991",
    payer_id: "LUMEN01",
    patient_id: "MQ-1001",
    subscriber_id: "SUB-MQ",
    check_number: "CHK-8801",
    check_date: "2025-10-28",
    total_billed: 260,
    total_allowed: 220,
    total_insurance_paid: 210,
    total_patient_responsibility: 10,
    total_adjustments: 40,
    note: "Periodic exam and cleaning. Already marked approved in the sample.",
    line_items: [
      {
        procedure_code: "D0120",
        procedure_description: "Periodic oral evaluation",
        tooth_number: null,
        date_of_service: "2025-10-14",
        billed_amount: 80,
        allowed_amount: 70,
        insurance_paid: 70,
        patient_responsibility: 0,
        deductible_applied: 0,
        copay: 0,
        coinsurance: 0,
        adjustment_amount: 10,
        adjustment_code: "CO-45",
        adjustment_description: "Contractual",
        remark_codes: null,
        remark_description: null,
        confidence_score: 0.97,
      },
      {
        procedure_code: "D1110",
        procedure_description: "Adult prophylaxis",
        tooth_number: null,
        date_of_service: "2025-10-14",
        billed_amount: 180,
        allowed_amount: 150,
        insurance_paid: 140,
        patient_responsibility: 10,
        deductible_applied: 10,
        copay: 0,
        coinsurance: 0,
        adjustment_amount: 30,
        adjustment_code: "CO-45",
        adjustment_description: "Contractual",
        remark_codes: null,
        remark_description: null,
        confidence_score: 0.94,
      },
    ],
  },
  {
    id: "cedar",
    patient_name: "Cedar Brook",
    payer_name: "Harbor Benefit",
    claim_number: "HRB-2208",
    date_of_service: "2025-12-03",
    created_at: "2026-01-09T15:00:00.000Z",
    check_amount: 96,
    review_status: "flagged",
    confidence_score: 0.81,
    provider_name: practice,
    provider_npi: "1999999991",
    payer_id: "HARBOR",
    patient_id: "CB-2044",
    subscriber_id: "SUB-CB",
    check_number: "CHK-8802",
    check_date: "2025-12-20",
    total_billed: 140,
    total_allowed: 110,
    total_insurance_paid: 96,
    total_patient_responsibility: 14,
    total_adjustments: 30,
    note: "Flagged in the sample because the tooth number was left blank.",
    line_items: [
      {
        procedure_code: "D2392",
        procedure_description: "Resin composite, two surfaces",
        tooth_number: null,
        date_of_service: "2025-12-03",
        billed_amount: 140,
        allowed_amount: 110,
        insurance_paid: 96,
        patient_responsibility: 14,
        deductible_applied: 0,
        copay: 0,
        coinsurance: 14,
        adjustment_amount: 30,
        adjustment_code: "CO-45",
        adjustment_description: "Contractual",
        remark_codes: null,
        remark_description: null,
        confidence_score: 0.78,
      },
    ],
  },
  {
    id: "rowan",
    patient_name: "Rowan Pebble",
    payer_name: "Paper & Pine Mutual",
    claim_number: "PPM-4410",
    date_of_service: "2026-01-19",
    created_at: "2026-02-02T15:00:00.000Z",
    check_amount: 840,
    review_status: "pending",
    confidence_score: 0.9,
    provider_name: practice,
    provider_npi: "1999999991",
    payer_id: "PAPER",
    patient_id: "RP-3300",
    subscriber_id: "SUB-RP",
    check_number: "CHK-8803",
    check_date: "2026-01-30",
    total_billed: 1200,
    total_allowed: 960,
    total_insurance_paid: 840,
    total_patient_responsibility: 120,
    total_adjustments: 240,
    note: "Still waiting in the sample queue. Approve it to include it in the export.",
    line_items: [
      {
        procedure_code: "D2750",
        procedure_description: "Crown, porcelain fused to metal",
        tooth_number: "14",
        date_of_service: "2026-01-19",
        billed_amount: 1200,
        allowed_amount: 960,
        insurance_paid: 840,
        patient_responsibility: 120,
        deductible_applied: 0,
        copay: 0,
        coinsurance: 120,
        adjustment_amount: 240,
        adjustment_code: "CO-45",
        adjustment_description: "Contractual",
        remark_codes: null,
        remark_description: null,
        confidence_score: 0.9,
      },
    ],
  },
  {
    id: "juniper",
    patient_name: "Juniper Moss",
    payer_name: "Kiln Cooperative",
    claim_number: "KLN-0091",
    date_of_service: "2026-03-01",
    created_at: "2026-03-18T15:00:00.000Z",
    check_amount: 40,
    review_status: "rejected",
    confidence_score: 0.62,
    provider_name: practice,
    provider_npi: "1999999991",
    payer_id: "KILN",
    patient_id: "JM-0188",
    subscriber_id: "SUB-JM",
    check_number: "CHK-8804",
    check_date: "2026-03-12",
    total_billed: 55,
    total_allowed: 40,
    total_insurance_paid: 40,
    total_patient_responsibility: 0,
    total_adjustments: 15,
    note: "Rejected in the sample. It stays out of the export until you approve it.",
    line_items: [
      {
        procedure_code: "D0140",
        procedure_description: "Limited oral evaluation",
        tooth_number: null,
        date_of_service: "2026-03-01",
        billed_amount: 55,
        allowed_amount: 40,
        insurance_paid: 40,
        patient_responsibility: 0,
        deductible_applied: 0,
        copay: 0,
        coinsurance: 0,
        adjustment_amount: 15,
        adjustment_code: "CO-45",
        adjustment_description: "Contractual",
        remark_codes: null,
        remark_description: null,
        confidence_score: 0.62,
      },
    ],
  },
];

export function claimToRecord(claim: DemoClaim): EOBExtractionRecord {
  return {
    id: claim.id,
    batch_id: "demo-batch",
    practice_id: "demo-practice",
    pdf_storage_path: "demo/fictional.pdf",
    payer_name: claim.payer_name,
    payer_id: claim.payer_id,
    patient_name: claim.patient_name,
    patient_dob: null,
    patient_id: claim.patient_id,
    subscriber_name: claim.patient_name,
    subscriber_id: claim.subscriber_id,
    group_number: "GRP-FICTION",
    claim_number: claim.claim_number,
    date_of_service: claim.date_of_service,
    provider_name: claim.provider_name,
    provider_npi: claim.provider_npi,
    check_number: claim.check_number,
    check_date: claim.check_date,
    check_amount: claim.check_amount,
    line_items: claim.line_items,
    total_billed: claim.total_billed,
    total_allowed: claim.total_allowed,
    total_insurance_paid: claim.total_insurance_paid,
    total_patient_responsibility: claim.total_patient_responsibility,
    total_adjustments: claim.total_adjustments,
    remarks: claim.note,
    denial_flags: [],
    confidence_score: claim.confidence_score,
    raw_extraction: {
      payer_name: claim.payer_name,
      payer_id: claim.payer_id,
      patient_name: claim.patient_name,
      patient_dob: null,
      patient_id: claim.patient_id,
      subscriber_name: claim.patient_name,
      subscriber_id: claim.subscriber_id,
      group_number: "GRP-FICTION",
      claim_number: claim.claim_number,
      date_of_service: claim.date_of_service,
      provider_name: claim.provider_name,
      provider_npi: claim.provider_npi,
      check_number: claim.check_number,
      check_date: claim.check_date,
      check_amount: claim.check_amount,
      line_items: claim.line_items,
      total_billed: claim.total_billed,
      total_allowed: claim.total_allowed,
      total_insurance_paid: claim.total_insurance_paid,
      total_patient_responsibility: claim.total_patient_responsibility,
      total_adjustments: claim.total_adjustments,
      remarks: claim.note,
      denial_flags: [],
      confidence_score: claim.confidence_score,
    },
    review_status: claim.review_status,
    reviewed_by: null,
    reviewed_at: null,
    created_at: claim.created_at,
  };
}
